usernames = [
    "bytewrangler",
    "pixelpotion",
    "echohound",
    "glitchwizard",
    "nebulanomad",
    "loothunter",
    "ramenrogue",
    "cosmicchill",
    "turbodino",
    "gamescribe",
    "nightowlnest",
    "codeshaman",
    "snarkypixel",
    "starshipstreak",
    "chillcastle",
    "rustycircuit",
    "arcaneabyss",
    "laserlynx",
    "noodleninja",
    "stormcaster",
    "dustypalette",
    "manamancer",
    "frostedglitch",
    "zenzephyr",
    "emberfox",
]

messages = [
    "Hey everyone! How's it going?",
    "Let's gooo! 🔥",
    "What's up, chat?",
    "First time catching the stream live! Excited to be here!",
    "Anyone know what time they usually go live?",
    "This is honestly the highlight of my day.",
    "I'm hyped for this stream! Always a good time!",
    "Did I miss anything good?",
    "That move was insane! GG!",
    "Anyone else watching from [location]? Just curious!",
    "LOL that was close! 😆",
    "What's your favorite part about streaming?",
    "How long have you been streaming?",
    "Oh, I love this game! So fun to watch.",
    "Chat, what's everyone's snack of choice today?",
    "Wow, the production quality is on point!",
    "Any tips for beginners? Just started getting into this!",
    "Let's show some love and drop those follows!",
    "BRB, gotta grab a drink!",
    "Big F in the chat for that one. 😅",
    "Wait, how did you pull that off??",
    "Mods, you're doing an awesome job. Thanks!",
    "I love the community here. Y'all are so chill.",
    "That moment was clip-worthy! 😂",
    "Can we get some hype in the chat? 🔥",
]
